### ISSUE TITLE
Yarn package just broke

### ISSUE THREAD

**Issue by mr-bo-jangles** [ubirak/gulp-uglifycss#14]
```yarn install v0.21.3
info No lockfile found.
warning prezola.com: No license field
[1/4] Resolving packages...
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree. 28/03/2017, 11:08:08
warning browser-sync > localtunnel > request > node-uuid@1.4.8: Use uuid module instead
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/gulp-uglifycss/-/gulp-uglifycss-1.0.7.tgz: invalid tar file".
info If you think this is a bug, please open a bug report with the information provided in "/srv/src/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Removing intermediate container ab2294a90d76```

**Comment by poltro90** [comment]
Same issue applies to npm

`npm install
npm ERR! tar.unpack untar error /Users/mb/.npm/gulp-uglifycss/1.0.7/package.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20

npm ERR! invalid tar file
`

**Comment by mathieu-gilloots** [comment]
Here too

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
my `npm install` is broken too

**Comment by Spy-Seth** [comment]
I've publish a maintenance version yesterday (v1.0.7). I've used `yarn publish` to publish it. I think this could be an explanation of this.

I just publish a new version (v1.0.8) of the package using `npm publish` as before. Please tell me if this solve the issue.

**Comment by Spy-Seth** [comment]
The problem of corrupted package seems to already be reported on yarn site: https://github.com/yarnpkg/yarn/issues/2764#issuecomment-290008862 

Wait and see!

**Comment by sweoggy** [comment]
Hi @Spy-Seth, v1.0.8 works just fine over here where 1.0.7 did not, thanks!
