### ISSUE TITLE
Remove gulp-util as it is been deprecated

### ISSUE THREAD

**Issue by sureshofficial** [ubirak/gulp-uglifycss#19]
Follow this article: https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by Spy-Seth** [comment]
This have been fix by https://github.com/ubirak/gulp-uglifycss/pull/18. We forgot to release the fix. I will do it

**Comment by Spy-Seth** [comment]
v1.1.0 released: https://github.com/ubirak/gulp-uglifycss/releases/tag/v1.1.0
